import type { JobCardData } from "../types/jobs";

// Shown instantly while the first backend fetch is in flight, and as a
// fallback if the opportunities table is genuinely empty (e.g. right after
// launch, before an admin has added anything or a sync has run).
export const dummyJobs: JobCardData[] = [
  {
    id: "dummy-1",
    title: "Senior UI/UX Designer",
    company: "TechCorp Solutions",
    location: "Remote",
    postedAt: "2 hours ago",
    description: "Design user-centered interfaces and product experiences.",
    jobType: "Full-time",
    category: "Jobs",
    tags: ["Full-time", "Remote"],
    applyUrl: "#",
    isFeatured: false,
    source: "dummy",
  },
  {
    id: "dummy-2",
    title: "Frontend Developer",
    company: "Digital Innovations Inc",
    location: "New York, NY",
    postedAt: "5 hours ago",
    description: "Build modern frontend interfaces with React and TypeScript.",
    jobType: "Full-time",
    category: "Jobs",
    tags: ["Full-time", "GMBTE"],
    applyUrl: "#",
    isFeatured: false,
    source: "dummy",
  },
  {
    id: "dummy-3",
    title: "React Native Developer",
    company: "Enterprise Software Co",
    location: "Remote",
    postedAt: "3 days ago",
    description: "Create mobile applications with React Native and APIs.",
    jobType: "Full-time",
    category: "Jobs",
    tags: ["Full-time", "Remote"],
    applyUrl: "#",
    isFeatured: false,
    source: "dummy",
  },
  {
    id: "dummy-4",
    title: "UI Developer (Internship)",
    company: "Tech Academy",
    location: "Remote",
    postedAt: "1 week ago",
    description: "Assist with UI implementation and design systems.",
    jobType: "Internship",
    category: "Internships",
    tags: ["Internship", "Remote", "GMBTE"],
    applyUrl: "#",
    isFeatured: false,
    source: "dummy",
  },
];
