import type { JobCardData } from "../types/jobs";

export const dummyJobs: JobCardData[] = [
  {
    id: "dummy-1",
    title: "Senior UI/UX Designer",
    company: "TechCorp Solutions",
    location: "Remote",
    postedAt: "2 hours ago",
    description: "Design user-centered interfaces and product experiences.",
    salary: "$80,000 - $120,000",
    jobType: "Full-time",
    tags: ["Full-time", "Remote", "External"],
    match: 87,
    applyUrl: "#",
    source: "dummy",
  },
  {
    id: "dummy-2",
    title: "Frontend Developer",
    company: "Digital Innovations Inc",
    location: "New York, NY",
    postedAt: "5 hours ago",
    description: "Build modern frontend interfaces with React and TypeScript.",
    salary: "$90,000 - $130,000",
    jobType: "Full-time",
    tags: ["Full-time", "GMBTE"],
    match: 76,
    applyUrl: "#",
    source: "dummy",
  },
  {
    id: "dummy-3",
    title: "React Native Developer",
    company: "Enterprise Software Co",
    location: "Remote",
    postedAt: "3 days ago",
    description: "Create mobile applications with React Native and APIs.",
    salary: "$85,000 - $115,000",
    jobType: "Full-time",
    tags: ["Full-time", "Remote", "External"],
    match: 99,
    applyUrl: "#",
    source: "dummy",
  },
  {
    id: "dummy-4",
    title: "UI Developer (Internship)",
    company: "Tech Academy",
    location: "Remote",
    postedAt: "1 week ago",
    description: "Assist with UI implementation and design systems.",
    salary: "$20/hour",
    jobType: "Internship",
    tags: ["Internship", "Remote", "GMBTE"],
    match: 87,
    applyUrl: "#",
    source: "dummy",
  },
];